name: Testing stuff

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: youngest commit message
        env:
          YOUNGEST_COMMIT_MSG: ${{ toJson(github.event.head_commit.message) }}
        run: echo "$YOUNGEST_COMMIT_MSG"
      - name: Keyword skip in the latest commit message
        if: ${{ contains(github.event.head_commit.message, '#skip') }}
        run: echo "This should be printed if there was a skip included in the commit message"
      - name: NO Keyword skip in the latest commit message
        if: ${{ !contains(github.event.head_commit.message, '#skip') }}
        run: echo "This SHOULD NOT be printed if there was a skip included in the commit message"
        # A Pull request might contain multiple commit messages. If any of those include the "#skip" keyword we should
        # not be doing tagging or deployment
      - name: Keyword skip in one of the commit messages
        if: contains(join(github.event.commits.*.message, ','), '#skip')
        run: echo "At least one of the commit messages contains the skip keyword"
      - name: NO keyword in the commit messages
        if: ${{!contains(join(github.event.commits.*.message, ','), '#skip')}}
        run: echo "None of the commit messages contains the skip keyword"
