name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: youngest commit message
        env:
          YOUNGEST_COMMIT_MSG: ${{ toJson(github.event.head_commit.message) }}
        run: echo "$YOUNGEST_COMMIT_MSG"
      - name: conditional test
        if: ${{ contains(github.event.head_commit.message, '#skip') }}
        run: echo "This should be printed if there was a skip included in the commit message"
      - name: conditional test 2
        if: ${{ !contains(github.event.head_commit.message, '#skip') }}
        run: echo "This SHOULD NOT be printed if there was a skip included in the commit message"
