name: Periodic health check

on:
  push:
    branches:
      - not_a_branch # Disable this pipeline from getting triggered on push to master (Exercise 11.19 done)
  # Run every five minutes on Wednesdays in March 29.
  # Disable the scheduled health checks after completing 11.19
  #schedule:
  #  - cron: "5 * 29 3 3"
  #  - cron: "10 * * * *" # Run every 10 minutes

jobs:
  health_check_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          # Check the following URLs one by one sequentially
          url: https://cicd-pokedex.herokuapp.com/
